### ISSUE TITLE
De la version alpha a une beta

### ISSUE THREAD

**Issue by PPAC37** [PPAC37/li3d.fr-forum-glossaire#6]
La version actuelle n'est qu'un genre de brouillon qu'il me faut grandement retravailler.

## TODO code source
 * [ ] nettoyer le pom.xml des dépendance non utilisé. (pour réduire le temps de compilation et la taille du .jar qui inclue les dépendances)
 * [ ] Nettoyer le code ( enlever les blocs non utilisé, factoriser, ... )
 * [ ] Javadoc
 * [ ] Obtenir l'entête du sommaire depuis le sujet et non comme actuellement codé en dur
 * [ ] Test unitaire ( pour déterminé la compatibilité du parse avec le code html du forum ... cf si une mise a jours du forum change les id ou les tag qui plante le parser le détecter ...)

## Action GitHub et le jar
 * [ ] Trouver une méthode pour que les fichiers de sortie utilisé par les Action GitHub ne plante pas ( sur un changement de nom de fichier de sortie ) car actuellement c'est pas top a maintenir... ( revoir les actions pour utiliser des script dans les src ? )
 * [ ] Voir si possibilité de mettre a jours automatiquement le commentaire du sujet du glossaire qui contiens le sommaire via une action github ( mais comment gérer l’authentification sur le forum depuis une action sans risquer de laisser un login/mdp ou session de cookie en public dans le dépôts... )

## TODO fonctionnalité a implémenter
 * [ ] Une version du glossaire .zip ( en html Sommaire + Définition et Images) a télécharger ( pour navigation hors ligne )
 * [ ] Une version du glossaire PDF
 * [ ] Contrôler la disponibilité des lien et ressource externe dans les définition ( images, video youtube )
 * [ ] QRCode vers la ressource ( VideoYoutu ) si version Hors Ligne ou papier
 * [ ] ...
