### ISSUE TITLE
Les liens retours au sommaire des définitions sur le sujet du glossaire du forum a revoir.

### ISSUE THREAD

**Issue by PPAC37** [PPAC37/li3d.fr-forum-glossaire#7]
Les **"Retour au sommaire du glossaire"** des définitions du sujet du glossaire pourais être transformé pour faciliter la navigation.

Utiliser le lien

https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/#comment-478055

ou au pire 

https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/?sortby=date#comments

Pour avoir déjà la page partiellement défilé et tomber plus vite sur le sommaire.

car actuellement l'on se retrouve en haut de page avec le lien utilisé et il faut faire défiler la page pour retomber sur le sommaire

https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/ 

L'idéal serai d'avoir un <code>id=\"Sommaire\"</code> dans le Titre <code>h2</code> du sommaire et des <code>h3</code> des groupes de définition. ( cf A , B , ... Z )

# TODO 
modifier le "Retour au sommaire du glossaire" des 67 définition présente
 * [ ] [comment-id=478055 - [] ](https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/?do=findComment&comment=478055)
 * [ ] [comment-id=478059 - [Bowden] ](https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/?do=findComment&comment=478059)
 * [ ] [comment-id=478060 - [Bordure, Brim] ](https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/?do=findComment&comment=478060)
 * [ ] [comment-id=478061 - [CAO, Conception Assistée par Ordinateur] ](https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/?do=findComment&comment=478061)
 * [ ] [comment-id=478062 - [CFF, Composite Filament Fabrication] ](https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/?do=findComment&comment=478062)
 * [ ] [comment-id=478063 - [CJP, ColorJet Printing] ](https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/?do=findComment&comment=478063)
 * [ ] [comment-id=478064 - [CNC, Computer Numerical Command] ](https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/?do=findComment&comment=478064)
 * [ ] [comment-id=478065 - [Crowdfunding] ](https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/?do=findComment&comment=478065)
 * [ ] [comment-id=478066 - [DLP] ](https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/?do=findComment&comment=478066)
 * [ ] [comment-id=478067 - [DMLS, Direct Metal Laser Sintering] ](https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/?do=findComment&comment=478067)
 * [ ] [comment-id=478068 - [DRM, Digital Rights Management] ](https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/?do=findComment&comment=478068)
 * [ ] [comment-id=478070 - [Elephant’s foot, Pied d'éléphant] ](https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/?do=findComment&comment=478070)
 * [ ] [comment-id=478071 - [Epaisseur de couche, Layer height] ](https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/?do=findComment&comment=478071)
 * [ ] [comment-id=478072 - [Extrusion] ](https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/?do=findComment&comment=478072)
 * [ ] [comment-id=478073 - [FabLab, Fabrication Laboratory] ](https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/?do=findComment&comment=478073)
 * [ ] [comment-id=478074 - [Dépot de filament fondu, FDM, FFF, Fused Deposition Modeling, Fused Filament Fabrication, Imprimante FDM] ](https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/?do=findComment&comment=478074)
 * [ ] [comment-id=478076 - [Extrudeur ?, Feeder] ](https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/?do=findComment&comment=478076)
 * [ ] [comment-id=478077 - [Filament] ](https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/?do=findComment&comment=478077)
 * [ ] [comment-id=478078 - [FCP, Fast Ceramic Production] ](https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/?do=findComment&comment=478078)
 * [ ] [comment-id=478079 - [ALM, AM] ](https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/?do=findComment&comment=478079)
 * [ ] [comment-id=478080 - [FTI, Film Transfert Imaging] ](https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/?do=findComment&comment=478080)
 * [ ] [comment-id=478081 - [G-Code] ](https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/?do=findComment&comment=478081)
 * [ ] [comment-id=478082 - [HIPS] ](https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/?do=findComment&comment=478082)
 * [ ] [comment-id=478083 - [Infill, Remplissage] ](https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/?do=findComment&comment=478083)
 * [ ] [comment-id=478084 - [Tension secteur] ](https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/?do=findComment&comment=478084)
 * [ ] [comment-id=478085 - [Machine-outil] ](https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/?do=findComment&comment=478085)
 * [ ] [comment-id=478086 - [Maker] ](https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/?do=findComment&comment=478086)
 * [ ] [comment-id=478087 - [Maker Faire] ](https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/?do=findComment&comment=478087)
 * [ ] [comment-id=478088 - [Microsoft 3MF] ](https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/?do=findComment&comment=478088)
 * [ ] [comment-id=478089 - [MJM, MultiJet Modeling] ](https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/?do=findComment&comment=478089)
 * [ ] [comment-id=478090 - [MSLA, Masked SLA] ](https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/?do=findComment&comment=478090)
 * [ ] [comment-id=478093 - [Buse, Nozzle] ](https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/?do=findComment&comment=478093)
 * [ ] [comment-id=478094 - [Oozing] ](https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/?do=findComment&comment=478094)
 * [ ] [comment-id=478095 - [Open Source] ](https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/?do=findComment&comment=478095)
 * [ ] [comment-id=478096 - [Overhang, Surplomb] ](https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/?do=findComment&comment=478096)
 * [ ] [comment-id=478097 - [PC (Plastique)] ](https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/?do=findComment&comment=478097)
 * [ ] [comment-id=478098 - [Pillowing] ](https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/?do=findComment&comment=478098)
 * [ ] [comment-id=478099 - [PLA, PolyLactic Acid] ](https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/?do=findComment&comment=478099)
 * [ ] [comment-id=478100 - [Bed, Heatbed, Plateau] ](https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/?do=findComment&comment=478100)
 * [ ] [comment-id=478102 - [Plasticine] ](https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/?do=findComment&comment=478102)
 * [ ] [comment-id=478103 - [PVA, Polyacétate de Vinyle] ](https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/?do=findComment&comment=478103)
 * [ ] [comment-id=478104 - [Radeau, Raft] ](https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/?do=findComment&comment=478104)
 * [ ] [comment-id=478105 - [Shell] ](https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/?do=findComment&comment=478105)
 * [ ] [comment-id=478107 - [Slicer, Trancheur] ](https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/?do=findComment&comment=478107)
 * [ ] [comment-id=478108 - [Jupe, Skirt] ](https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/?do=findComment&comment=478108)
 * [ ] [comment-id=478109 - [Fusion sélective par laser, SLM, Selective Laser Melting] ](https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/?do=findComment&comment=478109)
 * [ ] [comment-id=478110 - [FLS, Frittage Laser Sélectif, SLS, Selective Laser Sintering] ](https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/?do=findComment&comment=478110)
 * [ ] [comment-id=478112 - [SLA, Stéréolithographie] ](https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/?do=findComment&comment=478112)
 * [ ] [comment-id=478114 - [STL] ](https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/?do=findComment&comment=478114)
 * [ ] [comment-id=478116 - [Cheveux d'ange, Cordage, Stringing] ](https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/?do=findComment&comment=478116)
 * [ ] [comment-id=478117 - [Voxel] ](https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/?do=findComment&comment=478117)
 * [ ] [comment-id=478119 - [Décollement, Gauchissement, Warping] ](https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/?do=findComment&comment=478119)
 * [ ] [comment-id=478120 - [Wobble] ](https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/?do=findComment&comment=478120)
 * [ ] [comment-id=478122 - [Axe X, X axis] ](https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/?do=findComment&comment=478122)
 * [ ] [comment-id=478123 - [Axe Y, Y axis] ](https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/?do=findComment&comment=478123)
 * [ ] [comment-id=478124 - [Axe Z, Z axis] ](https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/?do=findComment&comment=478124)
 * [ ] [comment-id=478397 - [ABS] ](https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/?do=findComment&comment=478397)
 * [ ] [comment-id=483417 - [Trancanage] ](https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/?do=findComment&comment=483417)
 * [ ] [comment-id=483448 - [Alcool isopropylique, IPA, Isopropanol] ](https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/?do=findComment&comment=483448)
 * [ ] [comment-id=484987 - [Polymérisation, UV, Ultra violets] ](https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/?do=findComment&comment=484987)
 * [ ] [comment-id=485840 - [Wrapping] ](https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/?do=findComment&comment=485840)
 * [ ] [comment-id=489399 - [ATMega1280, ATMega2560, Arduino] ](https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/?do=findComment&comment=489399)
 * [ ] [comment-id=491949 - [Octo4a, Octopi, Octoprint] ](https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/?do=findComment&comment=491949)
 * [ ] [comment-id=492562 - [VSCode, Visual Studio Code] ](https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/?do=findComment&comment=492562)
 * [ ] [comment-id=494393 - [Excentrique, Écrou excentrique] ](https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/?do=findComment&comment=494393)
 * [ ] [comment-id=495324 - [Bridge (en), Bridging (en), Pont (fr), Pontage (fr)] ](https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/?do=findComment&comment=495324)
 * [ ] [comment-id=498697 - [Formatage] ](https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/?do=findComment&comment=498697)
 * [ ] [comment-id=503473 - [PTFE, Tube PTFE] ](https://www.lesimprimantes3d.fr/forum/topic/45754-glossaire-de-limpression-3d/?do=findComment&comment=503473)
